base:
  file: "base.txt"
  beforerun: "rm -f -- base.txt"
  run: "go test -bench=. -run=NOTEST -count=10 -benchmem -timeout=10h > base.txt"
  maxrun: 3
  maxerr: 5

cmp:
  file: "latest.txt"
  beforerun: "rm -f -- latest.txt"
  run: "go test -bench=. -run=NOTEST -count=10 -benchmem -timeout=10h > latest.txt"
  maxrun: 3
  maxerr: 5

rbase:
  file: "rbase.txt"
  beforerun: "rm -f -- rbase.txt"
  run: "go test -bench=Map -run=NOTEST -timeout=10h -count=10 runtime > rbase.txt"
  maxrun: 3
  maxerr: 5

rcmp:
  file: "rlatest.txt"
  beforerun: "rm -f -- rlatest.txt"
  run: "go test -bench=Map -run=NOTEST -timeout=10h -count=10 runtime > rlatest.txt"
  maxrun: 3
  maxerr: 5
